# Generated by Django 3.2.3 on 2022-04-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotacts',
            new_name='Contacts',
        ),
    ]
