# Generated by Django 3.2.3 on 2022-05-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rememb_prot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='remb',
            new_name='remembprot',
        ),
    ]
