# Generated by Django 3.2.3 on 2022-06-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lncrna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimuli', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('time_point', models.CharField(max_length=50)),
                ('experiment_type', models.CharField(max_length=200)),
                ('cell_line', models.CharField(max_length=255)),
                ('lncrna_name', models.CharField(max_length=255)),
                ('ncbi_gene', models.CharField(blank=True, max_length=255, null=True)),
                ('ensembl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('foldchange', models.CharField(blank=True, max_length=255, null=True)),
                ('expression', models.CharField(max_length=50)),
                ('pubmed_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LncrnaTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('regulatory_mech', models.CharField(blank=True, max_length=255, null=True)),
                ('regulatory_type', models.CharField(blank=True, max_length=255, null=True)),
                ('Target_type', models.CharField(blank=True, max_length=255, null=True)),
                ('regulator_ensemble_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
