# Generated by Django 4.0.5 on 2022-07-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailfile', models.FileField(null=True, upload_to='documents/')),
                ('target', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
    ]
