# Generated by Django 3.2.3 on 2022-04-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lncrna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lncrna',
            name='lncrna_origin',
        ),
    ]
