# Generated by Django 3.2.3 on 2022-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrna', '0002_remove_lncrna_lncrna_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lncrna',
            name='foldchange',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
