# Generated by Django 3.2.3 on 2022-04-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrna', '0003_alter_lncrna_foldchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='LncrnaTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('regulatory_mech', models.CharField(blank=True, max_length=255, null=True)),
                ('regulatory_type', models.CharField(blank=True, max_length=255, null=True)),
                ('Target_type', models.CharField(blank=True, max_length=255, null=True)),
                ('regulator_ensemble_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
