# Generated by Django 3.2.3 on 2022-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrna', '0004_lncrnatarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='lncrna',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
