# Generated by Django 3.2.3 on 2022-04-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lncrna', '0005_lncrna_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lncrna',
            name='slug',
        ),
    ]
