# Generated by Django 3.2.3 on 2022-06-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0002_auto_20220614_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataanalysis',
            name='no_of_sample',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
