# Generated by Django 3.2.3 on 2022-06-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0003_dataanalysis_no_of_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataanalysis',
            name='no_of_sample',
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='resultData',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
