# Generated by Django 4.0.5 on 2022-07-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0007_dataanalysis_lablefreedata_dataanalysis_lableddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataanalysis',
            name='cna',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='sna',
            field=models.TextField(null=True),
        ),
    ]
