# Generated by Django 4.0.5 on 2022-07-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0008_dataanalysis_cna_dataanalysis_sna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataanalysis',
            name='cna',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='sna',
        ),
    ]
