# Generated by Django 4.0.5 on 2022-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0011_example_lablefreedata_example_lableddata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='number_of_sample',
            field=models.IntegerField(default=0),
        ),
    ]
