# Generated by Django 3.2.14 on 2022-07-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0014_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proteome.dataanalysis'),
        ),
    ]
