# Generated by Django 3.2.14 on 2022-07-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0015_plots_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='jobid',
            field=models.IntegerField(null=True),
        ),
    ]
