# Generated by Django 3.2.14 on 2022-07-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0016_alter_plots_jobid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plots',
        ),
        migrations.AddField(
            model_name='dataanalysis',
            name='finalresult',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='example',
            name='file',
            field=models.FileField(null=True, upload_to='example/'),
        ),
    ]
