# Generated by Django 3.2.14 on 2022-07-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteome', '0017_auto_20220722_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataanalysis',
            name='finalresult',
        ),
    ]
